# Generated by Django 3.2.10 on 2022-04-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='price',
            new_name='new_price',
        ),
        migrations.AddField(
            model_name='event',
            name='discription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
