# Generated by Django 3.2.10 on 2022-05-04 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view', '0003_auto_20220429_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='places',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='old_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='price_class',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Favouriteplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favourite', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commenteplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.places')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='favourite_place',
            field=models.ManyToManyField(through='view.Favouriteplace', to=settings.AUTH_USER_MODEL),
        ),
    ]
