# Generated by Django 3.2.10 on 2022-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20220504_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
