# Generated by Django 3.2.10 on 2022-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_offers_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
