# Generated by Django 3.2.10 on 2022-05-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_rename_favouritecategory_interrestcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='age_category',
            field=models.CharField(choices=[('Youths', 'Youths'), ('Adults', 'Adults'), ('All', 'All')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
