# Generated by Django 3.2.10 on 2022-05-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0011_places_age_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='view.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateTimeField(),
        ),
    ]
