# Generated by Django 3.2.10 on 2022-05-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0012_auto_20220524_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offers',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.places'),
        ),
    ]
